version: "3.7"

networks:
  gitea:
    external: false

services:

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
     image: mysql:5.7
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=gitea
       - MYSQL_USER=gitea
       - MYSQL_PASSWORD=gitea
       - MYSQL_DATABASE=gitea
     networks:
       - gitea
     volumes:
       - ./mysql:/var/lib/mysql

  drone_server:
    image: drone/drone:2
    container_name: drone
    volumes: 
      - ./drone-server:/data
    environment:
      - DRONE_GITEA_SERVER=gitea
      - DRONE_GITEA_CLIENT_ID=74b57866-7c8d-4e88-9a4c-3c1cdfb7b3f4
      - DRONE_GITEA_CLIENT_SECRET=ozviHt7Y7MX241zrYtsyWvEbGNZD86ToQosaen32P6A6
      - DRONE_RPC_SECRET=760d5e2dbac871f5d671078d97e6401b
      - DRONE_SERVER_HOST=drone:8080
      - DRONE_SERVER_PROTO=http
    ports:
      - "8080:80"
      # for HTTPS and SSH
      - "443:443"
      # - "222:22"
    restart: always
  
  drone_runner:
    image: drone/drone-runner-docker:1
    container_name: runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone_server
      - DRONE_RPC_SECRET=760d5e2dbac871f5d671078d97e6401b
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=my-runner
      - DRONE_UI_USERNAME=root
      - DRONE_UI_PASSWORD=root
    ports:
      - "3300:3000"
    restart: always