version: "3.7"

networks:
  gitea:
    external: false

services:

  drone_server:
    image: drone/drone:2
    container_name: drone
    networks:
      - gitea
    volumes: 
      - ./drone-server:/data
    environment:
      - DRONE_AGENTS_ENABLED=true
      - "DRONE_GOGS_SERVER=${DRONE_GOGS_SERVER}"
      - "DRONE_RPC_SECRET=${DRONE_RPC_SECRET}"
      - "DRONE_SERVER_HOST=${DRONE_SERVER_HOST}"
      - "DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}"
    ports:
      - "${EXPOSED_DRONE_PORT_SERVER}:80"
    restart: always
  
  drone_runner:
    image: drone/drone-runner-docker:1
    container_name: runner
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "DRONE_RPC_PROTO=${DRONE_SERVER_PROTO}"
      - "DRONE_RPC_HOST=${DRONE_SERVER_HOST}"
      - "DRONE_RPC_SECRET=${DRONE_RPC_SECRET}"
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=my-runner
      - "DRONE_UI_USERNAME=${DRONE_UI_USERNAME}"
      - "DRONE_UI_PASSWORD=${DRONE_UI_PASSWORD}"
    ports:
      - "${EXPOSED_DRONE_PORT_AGENT}:3000"
    restart: always