---
- name: Gitea
  hosts:
    - gitea
  become: true
  tasks:
    - name: Install Bash
      apk:
        name: bash
        update_cache: yes
    - name: Install Gitea
      apk:
        name: gitea
        update_cache: yes

    # TEMPORARY
    - name: Remove git group
      group:
        name: git
        state: absent
    - name: Remove git user
      user:
        name: git
        state: absent


    # git -> gitea
    - name: Create gitea group
      group:
        name: gitea
        state: present
    - name: Create gitea user
      user:
        name: gitea
        # Equivalent to --home /home/git
        create_home: yes
        # Equivalent to --shell /bin/bash
        shell: /bin/bash
        # Equivalent to --system
        system: yes
        # --disabled-password
        password: '*'
        # Equivalent to --gecos 'Git VC'
        comment: Git Version Control
        # --group
        groups: gitea
    - name: Create Gitea var dirs
      file:
        name: "/var/lib/gitea/{{ item }}"
        state: directory
        owner: gitea
        group: gitea
        mode: '0750'
      with_items:
        - custom
        - data
        - log
    - name: Create Gitea etc dir
      file:
        name: /etc/gitea
        state: directory
        owner: root
        group: gitea
        mode: '0770'
    - name: Output current date as a variable
      shell: date
      register: current_date
    - name: Generate Gitea LFS_JWT_SECRET
      shell: gitea generate secret LFS_JWT_SECRET
      register: gitea_lfs_jwt_secret
    - name: Generate Gitea INTERNAL_TOKEN
      shell: gitea generate secret INTERNAL_TOKEN
      register: gitea_internal_token
    - name: Create Gitea config file
      template:
        src: tmpl/app.ini.j2
        dest: /etc/gitea/app.ini
        owner: root
        group: gitea
        mode: '0640'
      vars:
        GENERATED_AT: "{{ current_date.stdout }}"
        LFS_JWT_SECRET: "{{ gitea_lfs_jwt_secret.stdout }}"
        INTERNAL_TOKEN: "{{ gitea_internal_token.stdout }}"
