---
- name: Gitea
  hosts:
    - gitea_new
  become: true
  tasks:
    - name: Enable main repo in /etc/apk/repositories
      lineinfile:
        dest: /etc/apk/repositories
        regexp: '^#\s*3\.15\/community.*$'
        line: 'http://alpine.42.fr/v3.15/community'

    - name: Install Bash, Gitea and SQLite
      apk:
        name:
          - bash
          - gitea
          - sqlite
        update_cache: yes

    # - name: Make sure Gitea is NOT started
    #   sysvinit:
    #     name: gitea
    #     state: stopped
    #     enabled: yes
    - name: Check gitea processes
      shell: ps aux | grep 'supervise-daemon gitea'
      register: gitea_daemon
    - debug: var=gitea_daemon
    # - name: Kill Gitea
    #   shell: |
    #     start-stop-daemon \
    #       --signal KILL
    #       --pidfile /run/gitea.pid 
    #   when: 
    # - name: Output current date as a variable
    #   shell: date
    #   register: current_date
    # - name: Generate Gitea LFS_JWT_SECRET
    #   shell: gitea generate secret LFS_JWT_SECRET
    #   register: gitea_lfs_jwt_secret
    # - name: Generate Gitea INTERNAL_TOKEN
    #   shell: gitea generate secret INTERNAL_TOKEN
    #   register: gitea_internal_token
    # - name: Check if Gitea config file exists
    #   stat: path=/etc/gitea/app.ini
    #   ignore_errors: true
    #   register: gitea_cfg
    # - debug: var=gitea_cfg
    # - name: Create Gitea config file
    #   template:
    #     src: tmpl/app.ini.j2
    #     dest: /etc/gitea/app.ini
    #     owner: root
    #     group: gitea
    #     mode: '0640'
    #   vars:
    #     GENERATED_AT: "{{ current_date.stdout }}"
    #     LFS_JWT_SECRET: "{{ gitea_lfs_jwt_secret.stdout }}"
    #     INTERNAL_TOKEN: "{{ gitea_internal_token.stdout }}"
    #   when: gitea_cfg.stat.exists == false

    - name: Create gitea database
      shell: |
        gitea migrate \
        --config /etc/gitea/app.ini
    # Insert INSTALL_LOCK after migrating DB
    - name: Insert INSTALL_LOCK
      lineinfile:
        path: /etc/gitea/app.ini
        regexp: '^INSTALL_LOCK'
        insertafter: '^INTERNAL_TOKEN.*'
        line: 'INSTALL_LOCK=true'
    - name: Check that admin user exists
      shell: |
        sqlite3 \
          /var/lib/gitea/db/gitea.db \
          'select count(*) from user;'
      register: gitea_count_users
    - debug: var=gitea_count_users
    - name: Create gitea admin user
      shell: |
        gitea admin user create --admin \
        --username root \
        --password root1234 \
        --email root@gitea.tls
      when: gitea_count_users.stdout != '1'
    # - name: Make sure Gitea is started
    #   sysvinit:
    #     name: gitea
    #     state: started
    #     enabled: yes
