---
- name: Install Docker
  hosts:
    - docker_new
  become: true
  tasks:
    - name: Echo the output - OAUTH2_CLIENT_ID
      shell: echo {{ hostvars['GITEA_HOST']['OAUTH2_CLIENT_ID'] }}
      register: GITEA_CLIENT_ID
    - debug: var=GITEA_CLIENT_ID
    - name: Echo the output - OAUTH2_CLIENT_SECRET
      shell: echo {{ hostvars['GITEA_HOST']['OAUTH2_CLIENT_SECRET'] }}
      register: GITEA_CLIENT_SECRET
    - debug: var=GITEA_CLIENT_SECRET.stdout
    ## BAD COPY-PASTA START ##
    - name: Disable 3.15/main repo in /etc/apk/repositories
      lineinfile:
        dest: /etc/apk/repositories
        regexp: '^(https?:\/\/[^/]*)\/v3\.15\/main.*$'
        line: '#\1/v3.15/main\n'
        backrefs: yes
    - name: Enable edge/main repo in /etc/apk/repositories
      lineinfile:
        dest: /etc/apk/repositories
        regexp: '^#(https?:\/\/([^/]*))\/edge\/main.*$'
        line: '\1/edge/main'
        state: present
        backrefs: yes
    - name: Enable edge/community repo in /etc/apk/repositories
      lineinfile:
        dest: /etc/apk/repositories
        regexp: '^#(https?:\/\/([^/]*))\/edge\/community.*$'
        line: '\1/edge/community'
        state: present
        backrefs: yes
    ## BAD COPY-PASTA END ##
    - name: Install Docker
      apk:
        name:
          - docker
          - docker-compose
        update_cache: yes
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install pip3
      apk:
        name: py3-pip
        state: present
    # - name: Update python3
    #   shell: apk add --update --no-cache python3
    - name: Create symbolic link from python3 to python
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
    - name: Run ensurepip
      shell: python3 -m ensurepip
    - name: Install setuptools by hand
      shell: pip3 install --no-cache --upgrade pip setuptools
    - name: Install Python dependencies
      pip:
        name:
          - requests
          - setuptools
          - docker
        state: present
        executable: /usr/bin/pip3
    - name: Run Drone Server in Docker
      docker_container:
        name: drone
        state: started
        image: drone/drone:2
        exposed_ports:
          - 80
        env:
          # DRONE_GITEA_CLIENT_SECRET={{ GITEA_CLIENT_SECRET.stdout }}
          DRONE_GITEA_SERVER=http://gitea:3000
          DRONE_GITEA_CLIENT_ID={{ GITEA_CLIENT_ID.stdout }}
          DRONE_GITEA_CLIENT_SECRET=pass
          DRONE_RPC_SECRET=secret
          DRONE_SERVER_HOST=drone:8080
          DRONE_SERVER_PROTO=http
        restart_policy: always
        volumes:
          - /opt/drone:/data
        network_mode: host
        container_default_behavior: no_defaults
    - name: Run Drone Runner in Docker
      docker_container:
        name: drone_runner
        state: started
        image: drone/drone-runner-docker:1
        exposed_ports:
          - 3300
        env:
          DRONE_RPC_PROTO=http
          DRONE_RPC_HOST=drone
          DRONE_RPC_SECRET=secret
          DRONE_RUNNER_CAPACITY=2
          DRONE_RUNNER_NAME=my-runner
          DRONE_UI_USERNAME=root
          DRONE_UI_PASSWORD=root
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
        container_default_behavior: no_defaults
