# Playbook pour création app OAuth2 Gitea
---
- name: OAuth2 Gitea
  hosts:
    - gitea_new
  become: true
  tasks:
    - name: SQLite and uuidgen
      apk:
        name:
          - sqlite
          - uuidgen
        update_cache: yes

    ## Redundant part with docker (py3-pip) ##
    - name: Install pip3
      apk:
        name: py3-pip
        state: present
    # - name: Update python3
    #   shell: apk add --update --no-cache python3
    - name: Create symbolic link from python3 to python
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
    - name: Run ensurepip
      shell: python3 -m ensurepip
    - name: Install setuptools by hand
      shell: pip3 install --no-cache --upgrade pip setuptools
    - name: Install Python/bcrypt
      pip:
        name: bcrypt
        state: present
        executable: /usr/bin/pip3
      ## Redundant ##
    - name: Generate Client ID for OAuth2 app (UUID)
      shell: uuidgen
      register: client_id
    - debug: var=client_id
    - name: Generate Client Secret for OAuth2 app (44-char)
      shell: openssl rand -hex 22
      register: client_secret
    - debug: var=client_secret
    - name: Generate hashed Secret with Bcrypt
      # shell: python3 -c "import crypt;print(crypt.crypt('{{ client_secret.stdout }}'))"
      shell: python3 -c "import bcrypt;print(bcrypt.hashpw('pass', bcrypt.gensalt()))"
      register: client_secret_hashed
    - debug: var=client_secret_hashed
    - name: Generate Unix timestamp
      shell: date +%s
      register: current_timestamp
    - debug: var=current_timestamp
    - name: Create query file
      template:
        src: tmpl/oauth2_app_insert.sql.j2
        dest: /tmp/oauth2_app_insert.sql
        owner: root
        group: root
        mode: '0400'
      vars:
        OAUTH2_APP_NAME: "My Super App 000"
        OAUTH2_CLIENT_ID: "{{ client_id.stdout }}"
        OAUTH2_CLIENT_SECRET_HASHED: "{{ client_secret_hashed.stdout }}"
        TIMESTAMP: "{{ current_timestamp.stdout }}"
    - name: Create OAuth2 application by direct DB query
      shell: |
        sqlite3 \
          /var/lib/gitea/db/gitea.db < /tmp/oauth2_app_insert.sql
    - name: Remove query file after creation
      file:
        path: /tmp/oauth2_app_insert.sql
        state: absent
    # For sharing variables: http://bit.do/ansible-pass-vars
    - name: Register dummy host with variable
      add_host:
        name: "GITEA_HOST"
        OAUTH2_CLIENT_ID: " {{ client_id.stdout }}"
        OAUTH2_CLIENT_SECRET: " {{ client_secret.stdout }}"